version: "3.9"

services:
  telegram-bot:
    build: .
    # sh -c запускает команду через shell alias на python, а не через путь на интерпретатор
    env_file:
      - .env
    command: sh -c "python main.py"
    container_name: telegram-bot
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./database/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./database/backup:/database/backup
    ports:
      - "27017:27017"
    restart: on-failure

  redis:
    image: redis:latest
    command: redis-server --appendonly yes --replica-read-only no
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure


