version: "3.9"

networks:
  web:
    external: true

services:
  telegram-bot:
    build: .
    # sh -c запускает команду через shell alias на python, а не через путь на интерпретатор
    env_file:
      - .env
    command: sh -c "python main.py"
    container_name: telegram-bot
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - mongo
      - redis
    networks:
      - web

  mongo:
    image: mongo:6.0.4
    container_name: mongo
    volumes:
      - ./database/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./database/backup:/database/backup
    ports:
      - "27017:27017"
    networks:
      - web
    restart: on-failure

  redis:
    image: redis:7.0.9
    command: redis-server --appendonly yes --replica-read-only no
    container_name: redis
    ports:
      - "0.0.0.0:6379:6379"
    networks:
      - web
    restart: on-failure

